# Generated by Django 3.2.7 on 2021-09-13 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FileStorage',
            fields=[
                ('FileId', models.AutoField(primary_key=True, serialize=False)),
                ('FileName', models.CharField(max_length=100)),
                ('UpdateDate', models.DateField()),
            ],
        ),
    ]
